version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    restart: always
    container_name: backend
    env_file:
      - ./.env
    ports:
      - 5050:5050
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    env_file:
      - ./.env
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: